version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/marketplace_db?sslmode=disable" 
      PORT: "8080"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
    depends_on:
      - db


  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/

volumes:
  db_data:
